# To get an API key, see "Security" section
# of https://account.gandi.net/fr
api_key = ""

# Refresh interval in minutes
refresh_interval = 1

# Multiple domains can be defined this way
[[domains]]
name = "domain1.com"

# Multiple prefixes can be managed per domain
# v4.domain1.com will have only an A (ipv4) record
[[domains.prefixes]]
name = "v4"
ipv4 = true
ipv6 = false

# v6.domain1.com will have only an AAAA (ipv6) record
[[domains.prefixes]]
name = "v6"
ipv4 = true
ipv6 = false

# Manage a second domain
[[domains]]
name = "domain2.com"

# any.domain2.com will have both an A (ipv4)
# and AAAA (ipv6 domain)
[[domains.prefixes]]
name = "any"
ipv4 = true
ipv6 = true